name: student_app
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0 # تم تعديل الإصدار إلى الإصدار المتوافق مع بيئة Flutter الخاصة بك
  camera: ^0.11.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0   # Updated to the latest version of flutter_lints

transitive dependencies:
  async: ^2.13.0  
image_picker_for_web: ^3.0.6
material_color_utilities: ^0.12.0
mime: ^1.0.6

transitive dev_dependencies:
fake_async: ^1.3.3
leak_tracker: ^10.0.9
lints: ^5.1.1
vm_service: ^15.0.0


flutter:
  # The following section is specific to Flutter packages.
  uses-material-design: true

  # Add assets here (e.g., images or other resources)
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # You can add custom fonts to your application like so:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
